# Generated by Django 6.0 on 2026-04-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pago_preregistro_pago_referencia_pago_tipo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.IntegerField()),
                ('requiere_credencial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INSCRIPCION', 'Inscripción'), ('EXAMEN', 'Examen Médico'), ('MENSUALIDAD', 'Mensualidad')], max_length=20)),
                ('dias', models.IntegerField(blank=True, choices=[(1, '1 día'), (2, '2 días'), (3, '3 días'), (5, '5 días')], null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
