# Generated by Django 6.0 on 2026-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_producto_pago_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='mes_pagado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
