# Generated by Django 6.0 on 2026-02-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0006_remove_grupo_nivel_remove_inscripciongrupo_grupo_and_more'),
        ('calendario', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='grupo',
        ),
        migrations.AddField(
            model_name='horario',
            name='horario_carril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignaciones.horariocarril'),
        ),
    ]
