# Generated by Django 6.0 on 2026-04-24 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0008_horariocarril_dias'),
        ('calendario', '0003_remove_horario_grupo_horario_horario_carril'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
                ('maximo_nadadores', models.PositiveIntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
                ('horario_carril', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.horariocarril')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CANCELACION_DIA', 'Cancelación de día completo'), ('CANCELACION_HORARIO', 'Cancelación de horario')], max_length=30)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('horario_carril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignaciones.horariocarril')),
            ],
        ),
        migrations.CreateModel(
            name='RecuperacionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nivel', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('horario_carril', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.horariocarril')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.inscripcion')),
            ],
        ),
    ]
