# Generated by Django 6.0 on 2026-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_cuporecuperacion_eventocalendario_recuperacionclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='fechas_recuperacion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='permite_recuperacion',
            field=models.BooleanField(default=False),
        ),
    ]
