# Generated by Django 6.0 on 2026-04-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_eventocalendario_fechas_recuperacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='cupo_por_horario',
            field=models.PositiveIntegerField(blank=True, help_text='Cupos por horario y nivel SOLO si permite recuperación', null=True),
        ),
    ]
