# Generated by Django 6.0 on 2026-04-13 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0007_delete_grupo_delete_inscripciongrupo'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('respiracion', models.IntegerField(default=0)),
                ('libre', models.IntegerField(default=0)),
                ('espalda', models.IntegerField(default=0)),
                ('mariposa', models.IntegerField(default=0)),
                ('resistencia', models.IntegerField(default=0)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('horario_carril', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_tecnicas', to='asignaciones.horariocarril')),
                ('maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('nadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_tecnicas', to='usuarios.nadador')),
            ],
        ),
    ]
