# Generated by Django 6.0.2 on 2026-02-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_nadador_rename_fecha_registro_usuario_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDeportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resistencia', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('tecnica', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.nadador')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('presion_arterial', models.CharField(max_length=20)),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('diagnostico', models.TextField()),
                ('apto', models.BooleanField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.nadador')),
            ],
        ),
    ]
