# Generated by Django 6.0 on 2026-02-16 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondeportiva',
            name='nadador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.nadador'),
        ),
        migrations.AddField(
            model_name='evaluacionmedica',
            name='nadador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.nadador'),
        ),
    ]
