# Generated by Django 6.0 on 2026-02-16 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionmedica',
            name='nadador',
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_profesional', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_examen', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saturacion_oxigeno', models.IntegerField(blank=True, null=True)),
                ('grupo_rh', models.CharField(blank=True, max_length=10, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('afiliacion', models.CharField(blank=True, max_length=100, null=True)),
                ('conclusion', models.TextField()),
                ('nadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='usuarios.nadador')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medico.medico')),
            ],
        ),
        migrations.DeleteModel(
            name='EvaluacionDeportiva',
        ),
        migrations.DeleteModel(
            name='EvaluacionMedica',
        ),
    ]
