# Generated by Django 6.0 on 2026-02-16 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_remove_evaluacionmedica_nadador_medico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadomedico',
            name='estatus',
            field=models.CharField(choices=[('APTO', 'Apto'), ('NO_APTO', 'No Apto'), ('DIFICULTADES', 'Apto con Dificultades'), ('PARANATACION', 'Paranatación')], default='APTO', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificadomedico',
            name='motivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='nombre_completo',
            field=models.CharField(default='APTO', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'rol__nombre': 'Medico'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
