# Generated by Django 6.0 on 2026-04-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_certificadomedico_estatus_certificadomedico_motivos_and_more'),
        ('preregistro', '0003_rename_curp_preregistro_curp_documento_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadomedico',
            name='preregistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='preregistro.preregistro'),
        ),
        migrations.AlterField(
            model_name='certificadomedico',
            name='nadador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='usuarios.nadador'),
        ),
    ]
