# Generated by Django 6.0 on 2026-04-20 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_generacion']},
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='tipo_reporte',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='reportes/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='generado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='parametros',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('USUARIOS', 'Usuarios'), ('ACTIVIDAD', 'Actividad'), ('FINANCIERO', 'Financiero'), ('PERSONALIZADO', 'Personalizado')], db_index=True, default='PERSONALIZADO', max_length=20),
        ),
        migrations.AddField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(default='Reporte sin título', max_length=150),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='UsuarioActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_actividad', models.DateTimeField(db_index=True)),
                ('conectado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('USUARIOS', 'Usuarios'), ('PLANES', 'Planes'), ('REPORTES', 'Reportes'), ('SISTEMA', 'Sistema'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CONSULTA', 'Consulta')], db_index=True, max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', 'fecha'], name='reportes_hi_usuario_603942_idx'), models.Index(fields=['modulo', 'fecha'], name='reportes_hi_modulo_4e7e91_idx')],
            },
        ),
    ]
