# Generated by Django 6.0 on 2026-04-13 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(upload_to='preregistro/foto/')),
                ('acta_nacimiento', models.ImageField(blank=True, null=True, upload_to='preregistro/acta/')),
                ('curp', models.ImageField(blank=True, null=True, upload_to='preregistro/curp/')),
                ('identificacion', models.ImageField(upload_to='preregistro/ine/')),
                ('dias_seleccionados', models.CharField(max_length=100)),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('firma_digital', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_PAGO', 'Pendiente de pago'), ('EN_REVISION', 'En revisión médica'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.categoria')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.plancurso')),
            ],
        ),
    ]
