# Generated by Django 6.0 on 2026-04-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
