# Generated by Django 6.0 on 2026-04-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0002_alter_preregistro_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preregistro',
            old_name='curp',
            new_name='curp_documento',
        ),
        migrations.AddField(
            model_name='preregistro',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='es_menor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='foto_tutor',
            field=models.ImageField(blank=True, null=True, upload_to='preregistro/tutor_foto/'),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='ine_tutor',
            field=models.ImageField(blank=True, null=True, upload_to='preregistro/tutor/'),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='nombre_tutor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_EXAMEN', 'Pendiente examen'), ('PAGO_EXAMEN', 'Pago examen'), ('APTO', 'Apto'), ('NO_APTO', 'No apto'), ('PAGO_INSCRIPCION', 'Pago inscripción'), ('INSCRITO', 'Inscrito')], default='PENDIENTE_EXAMEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='identificacion',
            field=models.ImageField(blank=True, null=True, upload_to='preregistro/ine/'),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
    ]
