# Generated by Django 6.0 on 2026-04-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0003_rename_curp_preregistro_curp_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistro',
            name='contacto_emergencia_nombre',
            field=models.CharField(default='HOLA', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistro',
            name='contacto_emergencia_parentesco',
            field=models.CharField(default='HOLA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistro',
            name='contacto_emergencia_telefono',
            field=models.CharField(default='1234567890', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistro',
            name='contacto_emergencia_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
