# Generated by Django 6.0 on 2026-02-16 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='alberca',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='cupo_maximo',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='entrenador',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='grupo',
            name='horario_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AsignacionMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.grupo')),
                ('maestro', models.ForeignKey(limit_choices_to={'rol': 'MAESTRO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.grupo')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.nadador')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.grupo')),
                ('nadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.nadador')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asignaciones.nivel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SolicitudPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.evaluacion')),
                ('nadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.nadador')),
                ('nivel_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_actual', to='asignaciones.nivel')),
                ('nivel_sugerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_sugerido', to='asignaciones.nivel')),
            ],
        ),
        migrations.DeleteModel(
            name='Alberca',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
