# Generated by Django 6.0.2 on 2026-03-11 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_carril_asignacion'),
        ('usuarios', '0002_nadador_rename_fecha_registro_usuario_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alberca',
            options={'verbose_name': 'Alberca', 'verbose_name_plural': 'Albercas'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterField(
            model_name='carril',
            name='profundidad',
            field=models.DecimalField(decimal_places=2, help_text='Profundidad en metros', max_digits=4),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('competencia', 'Competencia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='alberca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='asignaciones.alberca'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='asignaciones.curso'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='asignaciones.grupo'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='nadador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='usuarios.nadador'),
        ),
    ]
