# Generated by Django 6.0 on 2026-02-16 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_nivel_remove_grupo_alberca_remove_grupo_curso_and_more'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='asignacionmaestro',
            name='maestro',
            field=models.ForeignKey(limit_choices_to={'rol__nombre': 'Maestro'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HorarioCarril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('carril', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.carril')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionCarril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('horario_carril', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.horariocarril')),
                ('nadador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.nadador')),
            ],
            options={
                'unique_together': {('nadador', 'horario_carril')},
            },
        ),
    ]
