# Generated by Django 6.0 on 2026-02-16 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_carril_alter_asignacionmaestro_maestro_horariocarril_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horariocarril',
            name='maestro',
            field=models.ForeignKey(default=1, limit_choices_to={'rol__nombre': 'Maestro'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
