# Generated by Django 6.0 on 2026-02-16 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_horariocarril_maestro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='inscripciongrupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='inscripciongrupo',
            name='nadador',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='maestro',
        ),
        migrations.RemoveField(
            model_name='solicitudpromocion',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='solicitudpromocion',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='horario_carril',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asignaciones.horariocarril'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcioncarril',
            name='horario_carril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignaciones.horariocarril'),
        ),
        migrations.AlterField(
            model_name='solicitudpromocion',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='horariocarril',
            unique_together={('carril', 'hora_inicio', 'hora_fin')},
        ),
        migrations.DeleteModel(
            name='AsignacionMaestro',
        ),
    ]
