# Generated by Django 6.0 on 2026-02-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0006_remove_grupo_nivel_remove_inscripciongrupo_grupo_and_more'),
        ('calendario', '0003_remove_horario_grupo_horario_horario_carril'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='InscripcionGrupo',
        ),
    ]
