# Generated by Django 6.0 on 2026-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0007_delete_grupo_delete_inscripciongrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariocarril',
            name='dias',
            field=models.CharField(choices=[('L-V', 'Lunes a Viernes'), ('L-M-V', 'Lunes, Miércoles y Viernes'), ('M-J', 'Martes y Jueves'), ('SAB', 'Sábado')], default='L-V', max_length=10),
            preserve_default=False,
        ),
    ]
